#ifndef GOOGLE_APIS_INTERNAL_GOOGLE_CHROME_API_KEYS_H_
#define GOOGLE_APIS_INTERNAL_GOOGLE_CHROME_API_KEYS_H_

#define GOOGLE_API_KEY "AIzaSyA2KlwBX3mkFo30om9LUFYQhpqLoa_BNhE"
#define GOOGLE_CLIENT_ID_MAIN "77185425430.apps.googleusercontent.com"
#define GOOGLE_CLIENT_SECRET_MAIN "OTJgUOQcT7lO7GsGZq2G4IlT"

#define GOOGLE_DEFAULT_API_KEY GOOGLE_API_KEY
#define GOOGLE_DEFAULT_CLIENT_ID GOOGLE_CLIENT_ID_MAIN
#define GOOGLE_DEFAULT_CLIENT_SECRET GOOGLE_CLIENT_SECRET_MAIN

#define GOOGLE_API_KEY_REMOTING "AIzaSyAoP6runCgAiXKUSuqLcgr1Hvr3dsS8AL78"
#define GOOGLE_CLIENT_ID_REMOTING "440925447803-avn2sjlkc099s0r7v62je5s339mu0am1.apps.googleusercontent.com"
#define GOOGLE_CLIENT_SECRET_REMOTING "Bgur6DFiOMM1h8x-AQpuTQ1K"

#define GOOGLE_CLIENT_ID_REMOTING_HOST "440925447803-m890isgsr23kdkcu2erd4mirnrjalf98.apps.googleusercontent.com"
#define GOOGLE_CLIENT_SECRET_REMOTING_HOST "TgKrL73H2kJe6Ir0ufp7bf6e"

#define GOOGLE_API_KEY_SODA "ce04d119-129f-404e-b4fe-6b913fffb6cb"

#endif  // GOOGLE_APIS_INTERNAL_GOOGLE_CHROME_API_KEYS_H_