#ifndef GOOGLE_APIS_INTERNAL_METRICS_SIGNING_KEY_H_
#define GOOGLE_APIS_INTERNAL_METRICS_SIGNING_KEY_H_

#define GOOGLE_METRICS_SIGNING_KEY ""

#endif  // GOOGLE_APIS_INTERNAL_METRICS_SIGNING_KEY_H_